apiVersion: v1
values:
  images:
    velero: velero/velero:v1.11.1
    kubectl: docker.io/bitnami/kubectl:1.28.4
    awsPlugin: velero/velero-plugin-for-aws:v1.7.1
    csiPlugin: velero/velero-plugin-for-csi:v0.5.1
patches:
  values.yaml:
    velero:
      image:
        repository: "{{ registryFrom .images.velero }}/{{ repositoryFrom .images.velero }}"
        tag: "{{ tagFrom .images.velero }}"
      initContainers:
        - name: velero-plugin-for-aws
          image: "{{ .images.awsPlugin }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - mountPath: /target
            name: plugins
        - name: velero-plugin-for-csi
          image: "{{ .images.csiPlugin }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      kubectl:
        image:
          repository: "{{ registryFrom .images.kubectl }}/{{ repositoryFrom .images.kubectl }}"
          tag: "{{ tagFrom .images.kubectl }}"
