apiVersion: v1
values:
  images:
    velero: docker.io/velero/velero:v1.18.0
    kubectl: docker.io/cloudogu/k8s-velero-kubectl:1.35.2
    awsPlugin: velero/velero-plugin-for-aws:v1.14.0
patches:
  values.yaml:
    velero:
      image:
        repository: "{{ registryFrom .images.velero }}/{{ repositoryFrom .images.velero }}"
        tag: "{{ tagFrom .images.velero }}"
      initContainers:
        - name: velero-plugin-for-aws
          image: "{{ .images.awsPlugin }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      kubectl:
        image:
          repository: "{{ registryFrom .images.kubectl }}/{{ repositoryFrom .images.kubectl }}"
          tag: "{{ tagFrom .images.kubectl }}"
