# This file contains mapping information for log levels of this component
apiVersion: v1
metavalues:
  mainLogLevel:
    name: Log-Level
    description: The central configuration value to set the log level for this component
    keys:
      - path: velero.configuration.logLevel
        mapping:
          debug: debug
          info: info
          warn: warning
          error: error