apiVersion: v1
values:
  images:
    velero: velero/velero:v1.16.0
    kubectl: docker.io/bitnami/kubectl:1.33.1
    awsPlugin: velero/velero-plugin-for-aws:v1.12.1
    restoreExcludePlugin: cloudogu/velero-plugin-for-restore-exclude:1.0.0
patches:
  values.yaml:
    velero:
      image:
        repository: "{{ registryFrom .images.velero }}/{{ repositoryFrom .images.velero }}"
        tag: "{{ tagFrom .images.velero }}"
      initContainers:
        - name: velero-plugin-for-aws
          image: "{{ .images.awsPlugin }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
        - name: velero-plugin-for-restore-exclude
          image: "{{ .images.restoreExcludePlugin }}"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /target
              name: plugins
      kubectl:
        image:
          repository: "{{ registryFrom .images.kubectl }}/{{ repositoryFrom .images.kubectl }}"
          tag: "{{ tagFrom .images.kubectl }}"
