cesKeyVar: &appCesLabelKey "app"
cesValueVar: &appCesLabelValue "ces"
cloudoguPartOfKeyVar: &cloudoguPartOfLabelKey "k8s.cloudogu.com/part-of"
cloudoguPartOfValueVar: &cloudoguPartOfLabelValue "backup"

cesLabels: &cesLabels
  *appCesLabelKey: *appCesLabelValue
  *cloudoguPartOfLabelKey: *cloudoguPartOfLabelValue

velero:
  resources:
    limits:
      memory: 184M
    requests:
      cpu: 15m
      memory: 184M
  image:
    imagePullSecrets:
      - "ces-container-registries"
  nameOverride: "velero"
  fullnameOverride: "velero"
  labels:
    *cesLabels
  podLabels:
    *cesLabels
  metrics:
    service:
      labels:
        *cesLabels
    serviceMonitor:
      additionalLabels:
        *cesLabels
    nodeAgentPodMonitor:
      additionalLabels:
        *cesLabels
    prometheusRule:
      additionalLabels:
        *cesLabels
  kubectl:
    image:
      repository: docker.io/bitnami/kubectl
      tag: 1.33.1
    labels:
      *cesLabels
  serviceAccount:
    server:
      labels:
        *cesLabels
  nodeAgent:
    labels:
      *cesLabels
  # Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required.
  # If the value is a string then it is evaluated as a template.
  initContainers:
   - name: velero-plugin-for-aws
     image: velero/velero-plugin-for-aws:v1.12.1
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins
   - name: velero-plugin-for-restore-exclude
     image: cloudogu/velero-plugin-for-restore-exclude:1.0.0
     imagePullPolicy: IfNotPresent
     volumeMounts:
       - mountPath: /target
         name: plugins

  ##
  ## Parameters for the `default` BackupStorageLocation and VolumeSnapshotLocation,
  ## and additional server settings.
  ##
  configuration:
    # Parameters for the BackupStorageLocation(s). Configure multiple by adding other element(s) to the backupStorageLocation slice.
    # See https://velero.io/docs/v1.6/api-types/backupstoragelocation/
    backupStorageLocation:
      # name is the name of the backup storage location where backups should be stored. If a name is not provided,
      # a backup storage location will be created with the name "default". Optional.
      - name: default
        # provider is the name for the backup storage location provider.
        provider: aws
        # bucket is the name of the bucket to store backups in. Required.
        bucket: velero
        # caCert defines a base64 encoded CA bundle to use when verifying TLS connections to the provider. Optional.
        caCert:
        # prefix is the directory under which all Velero data should be stored within the bucket. Optional.
        prefix:
        # default indicates this location is the default backup storage location. Optional.
        default:
        # validationFrequency defines how frequently Velero should validate the object storage. Optional.
        validationFrequency:
        # accessMode determines if velero can write to this backup storage location. Optional.
        # default to ReadWrite, ReadOnly is used during migrations and restores.
        accessMode: ReadWrite
        credential:
          # name of the secret used by this backupStorageLocation.
          name:
          # name of key that contains the secret data to be used.
          key:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config:
          region: minio-default
          s3ForcePathStyle: true
          s3Url: http://192.168.56.1:9000 # Point to docker container on host
          #  kmsKeyId:
          #  resourceGroup:
          #  The ID of the subscription containing the storage account, if different from the cluster’s subscription. (Azure only)
          #  subscriptionId:
          #  storageAccount:
          publicUrl: http://localhost:9000
        #  Name of the GCP service account to use for this backup storage location. Specify the
        #  service account here if you want to use workload identity instead of providing the key file.(GCP only)
        #  serviceAccount:
        #  Option to skip certificate validation or not if insecureSkipTLSVerify is set to be true, the client side should set the
        #  flag. For Velero client Command like velero backup describe, velero backup logs needs to add the flag --insecure-skip-tls-verify
        #  insecureSkipTLSVerify:

    # Parameters for the VolumeSnapshotLocation(s). Configure multiple by adding other element(s) to the volumeSnapshotLocation slice.
    # See https://velero.io/docs/v1.6/api-types/volumesnapshotlocation/
    volumeSnapshotLocation:
      # name is the name of the volume snapshot location where snapshots are being taken. Required.
      - name: default
        # provider is the name for the volume snapshot provider.
        provider: aws
        credential:
          # name of the secret used by this volumeSnapshotLocation.
          name:
          # name of key that contains the secret data to be used.
          key:
        # Additional provider-specific configuration. See link above
        # for details of required/optional fields for your provider.
        config:
          region: minio-default
    features: EnableCSI

  # Info about the secret to be used by the Velero deployment, which
  # should contain credentials for the cloud provider IAM account you've
  # set up for Velero.
  credentials:
    # Whether a secret should be used. Set to false if, for examples:
    useSecret: true
    # Name of a pre-existing secret in the Velero namespace
    existingSecret:


volumesnapshotclass:
  name: default-snapshot-vsc
  driver: driver.longhorn.io
  parameters:
    type: bak

excludedFromRestores:
  - name: "ces-loadbalancer"
    kind: "Service"
    version: "*"
  - name: "k8s-backup-operator"
    kind: "Component"
    version: "*"
    group: "k8s.cloudogu.com"
  - name: "k8s-backup-operator-crd"
    kind: "Component"
    version: "*"
    group: "k8s.cloudogu.com"
  - name: "k8s-snapshot-controller"
    kind: "Component"
    version: "*"
    group: "k8s.cloudogu.com"
  - name: "k8s-snapshot-controller-crd"
    kind: "Component"
    version: "*"
    group: "k8s.cloudogu.com"
  - name: "k8s-velero"
    kind: "Component"
    version: "*"
    group: "k8s.cloudogu.com"
  - name: "ecosystem-certificate"
    kind: "Secret"
    version: "*"

networkPolicies:
  enabled: true