apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws_endpoint | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws_access_key_id | b64enc }}
  AWS_ENDPOINTS: {{ .Values.aws_secret_access_key | b64enc }}