apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "velero.fullname" . }}-deny-ingress
spec:
  podSelector:
    matchLabels:
      app: velero
  policyTypes:
    - Ingress
