{{- if and (not .Values.velero.credentials.useSecret) (.Values.velero.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velero.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
type: Opaque
data:
  cloud: {{ printf "%s\n%s\naws_access_key_id=%s\naws_secret_access_key=%s" "|" "[default]" .Values.aws_access_key_id .Values.aws_secret_access_key | b64enc | quote}}
{{/*  cloud: |*/}}
{{/*    [default]*/}}
{{/*    aws_access_key_id={{ .Values.aws_access_key_id }}*/}}
{{/*    aws_secret_access_key={{ .Values.aws_secret_access_key }}*/}}
{{- range $key, $value := .Values.credentials.extraEnvVars }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end -}}
