{{- if .Values.volumesnapshotclass }}
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: {{ .Values.volumesnapshotclass.name }}
  labels:
    {{- include "k8s-velero.labels" . | nindent 4 }}
    velero.io/csi-volumesnapshot-class: "true"
{{- if .Values.volumesnapshotclass.driver }}
driver:  {{ .Values.volumesnapshotclass.driver }}
{{- end }}
# Setting a DeletionPolicy of Retain on the VolumeSnapshotClass
# will preserve the volume snapshot in the storage system
# for the lifetime of the Velero backup and will prevent
# the deletion of the volume snapshot in the storage system
# in the event of a disaster where the namespace with the
# VolumeSnapshot object may be lost.
deletionPolicy: Retain
{{- if .Values.volumesnapshotclass.parameters }}
parameters:
  {{- if .Values.volumesnapshotclass.parameters.type }}
  type: {{ .Values.volumesnapshotclass.parameters.type }}
  {{- end }}
  {{- end }}
  {{- end }}