{{- if .Values.volumesnapshotclass }}
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: {{- .Values.volumesnapshotclass.name }}
  labels:
    velero.io/csi-volumesnapshot-class: "true"
{{- if .Values.volumesnapshotclass.driver }}
driver:  {{- .Values.volumesnapshotclass.driver }}
{{- end }}
deletionPolicy: Delete
{{- if .Values.volumesnapshotclass.parameters }}
parameters:
  {{- if .Values.volumesnapshotclass.parameters.type }}
  type: {{ .Values.volumesnapshotclass.parameters.type }}
  {{- end }}
  {{- end }}
  {{- end }}